Repository Azure/autorest.java, pull requests merged in 2020-11, with the labels that each got.

#765 v4 model override parent setter
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapperFactory.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentModelMapper.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentObjectMapper.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentModelTemplate.java
  generate
  generate.bat
  javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ObjectMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModel.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelPropertyReference.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModels.java
  javagen/src/main/java/com/azure/autorest/model/javamodel/JavaJavadocComment.java
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
  readme.md
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Cat.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Cookiecuttershark.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Dog.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/DotSalmon.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Goblinshark.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/MyDerivedType.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Salmon.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Sawshark.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Shark.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/Siamese.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/SmartSalmon.java
Labels: v4

#721 Implement paging code generation in service impl
  androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java
  androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java
  androidgen/src/main/java/com/azure/autorest/android/model/AndroidProxyMethod.java
  androidgen/src/main/java/com/azure/autorest/android/model/AndroidServiceClient.java
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidClientMethodTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceClientTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/AsyncPageRetrieverTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/PageResponseRetrieverTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/PageRetrieverTemplate.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
Labels: ChatOct6Beta.2, ChatReleaseVersion

#777 v4 fluentlite, getById convenient method for Azure resource
  fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/CollectionMethodOperationByIdTemplate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceCollectionImplementationTemplate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentResourceModelInterfaceTemplate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/util/Utils.java
  javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java
  readme.md
Labels: FluentGen, v4

#781 v4 fluent, support rename model
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaRenamer.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
  readme.md
Labels: FluentGen, v4

#793 v4 fluent lite, bug fixes
  fluent-tests/prepare-tests.bat
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/delete/ResourceDelete.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
Labels: FluentGen, v4

#799 v4 fluentlite bug fixes
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentModelPropertyRegion.java
  fluentgen/src/test/java/com/azure/autorest/fluent/util/FluentUtilsTests.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java
  javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
Labels: FluentGen, v4

#803 v4 fluentlite bug fixes
  fluentgen/pom.xml
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/ResourceOperation.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/create/ResourceCreate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/get/ResourceRefresh.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentApplyMethod.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentBaseMethod.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentCreateMethod.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/method/FluentRefreshMethod.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/fluentmodel/update/ResourceUpdate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/util/FluentUtils.java
  fluentnamer/package.json
  fluentnamer/pom.xml
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java
  javagen/src/main/java/com/azure/autorest/model/xmlmodel/XmlBlock.java
  javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
  javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
  javagen/src/test/java/com/azure/autorest/util/CodeNamerTests.java
Labels: v4

#810 v4, add common class/annotation of azure-core to reserved words
  javagen/src/main/java/com/azure/autorest/mapper/ChoiceMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java
  javagen/src/main/java/com/azure/autorest/util/CodeNamer.java
  preprocessor/src/main/java/com/azure/autorest/preprocessor/namer/CodeNamer.java
Labels: v4

#811 v4 fluentlite, support update changelog.md while keeping previous changelogs
  fluent-tests/prepare-tests.bat
  fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/javamodel/FluentJavaPackage.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Changelog.java
  fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/ChangelogTemplate.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/TextTemplate.java
  fluentgen/src/main/resources/Changelog.txt
  fluentgen/src/test/java/com/azure/autorest/fluent/TestUtils.java
  fluentgen/src/test/java/com/azure/autorest/fluent/model/projectmodel/ChangelogTests.java
  javagen/src/main/java/com/azure/autorest/model/xmlmodel/XmlBlock.java
  javagen/src/main/java/com/azure/autorest/template/PomTemplate.java
  readme.md
Labels: FluentGen, v4
