Repository Azure/autorest.java, pull requests merged in 2021-12, with the labels that each got.

#1274 Use JacksonXmlElementWrapper Instead of a Static Inner Wrapper Class
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
  vanilla-tests/src/main/java/fixtures/xmlservice/models/AppleBarrel.java
  vanilla-tests/src/main/java/fixtures/xmlservice/models/ListContainersResponse.java
  vanilla-tests/src/main/java/fixtures/xmlservice/models/StorageServiceProperties.java
Labels: v4

#1278 mgmt, ci test coverage
  eng/pipelines/fluent_integration.yaml
  fluentgen/pom.xml
  protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesAsyncClient.java
  protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java
  protocol-tests/src/main/java/fixtures/mediatypes/implementation/MediaTypesClientImpl.java
  vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java
Labels: Mgmt

#1285 client, limit Generated annotation to non-Android Client
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceAsyncClientTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidServiceSyncClientTemplate.java
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidTemplateFactory.java
  androidgen/src/main/java/com/azure/autorest/android/template/AndroidWrapperClientMethodTemplate.java
  javagen/src/main/java/com/azure/autorest/template/ServiceAsyncClientTemplate.java
  javagen/src/main/java/com/azure/autorest/template/ServiceSyncClientTemplate.java
  javagen/src/main/java/com/azure/autorest/template/WrapperClientMethodTemplate.java
Labels: Client, LLC

#1288 mgmt, codegen report
  .github/workflows/fluent-test-gen-all.yml
  fluent-tests/gen_all.py
  fluent-tests/report.md
Labels: Mgmt

#1293 mgmt, dedpulicate Operations_List
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/FluentTransformer.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/NamingConflictResolver.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/OperationNameNormalization.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/util/Utils.java
Labels: Mgmt

#1290 Update Customization README Samples
  customization-base/README.md
  customization-base/pom.xml
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
  customization-base/src/samples/java/com/azure/autorest/customization/ReadmeSamples.java
  pom.xml
  readme.md
Labels: Codegen Customizations, Docs

#1297 LLC, write title in swagger/readme
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/AutorestSettings.java
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/util/FluentJavaSettings.java
  javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java
  package.json
Labels: LLC
