Repository Azure/autorest.java, pull requests merged in 2021-04, with the labels that each got.

#988 Add replaceBody to MethodCustomization
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
Labels: Codegen Customizations

#996 Code Customization Performance Improvement and Ability to Replace Method Parameters
  customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/Editor.java
  customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/ls/EclipseLanguageClient.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/ls/EclipseLanguageServerFacade.java
Labels: Codegen Customizations

#1005 Add ConstructorCustomization
  customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/Editor.java
  customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java
Labels: Codegen Customizations, enhancement

#1008 Add removeMethod to ClassCustomization and Code Cleanup
  customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/PropertyCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/CodeCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java
Labels: Codegen Customizations, enhancement

#1011 v4 fluentlite, bug fix for resource actions
  eng/pipelines/fluent_integration.yaml
  fluent-tests/prepare-tests.bat
  fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
Labels: FluentGen, v4
