Repository Azure/autorest.java, pull requests merged in 2021-11, with the labels that each got.

#1242 Use JacksonXmlText when Swagger Contains x-ms-text: true in XML Section
  extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/XmlSerlializationFormat.java
  generate
  generate.bat
  javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ModelPropertyMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientModelProperty.java
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
  vanilla-tests/src/main/java/fixtures/complexxmltag/DefaultValueClient.java
  vanilla-tests/src/main/java/fixtures/complexxmltag/DefaultValueClientBuilder.java
  vanilla-tests/src/main/java/fixtures/complexxmltag/models/BlobName.java
  vanilla-tests/src/main/java/fixtures/complexxmltag/models/package-info.java
  vanilla-tests/src/main/java/fixtures/complexxmltag/package-info.java
  vanilla-tests/src/main/java/fixtures/xmlservice/models/ObjectWithXMsTextProperty.java
  vanilla-tests/src/test/java/fixtures/complexxmltag/ComplexXmlTagTests.java
  vanilla-tests/swagger/xml-tag-with-attribute-and-value.json
Labels: v4

#1246 llc, add blank readme sample
  javagen/src/main/java/com/azure/autorest/Javagen.java
  javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
  javagen/src/main/java/com/azure/autorest/template/ProtocolSampleBlankTemplate.java
Labels: LLC

#1247 all, update core version
  customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/Customization.java
  customization-base/src/main/resources/pom.xml
  customization-tests/pom.xml
  javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
  pom.xml
  protocol-resilience-test/pom.xml
  protocol-sdk-integration-tests/eng/versioning/version_client.txt
  protocol-tests/pom.xml
  vanilla-tests/pom.xml
Labels: Client, LLC

#1248 LLC, update readme
  readme.md
Labels: LLC

#1251 mgmt, move x-ms-examples-original-file option to global
  fluentnamer/readme.md
Labels: Mgmt

#1231 Support HttpMethod OPTIONS
  javagen/src/main/java/com/azure/autorest/mapper/MethodGroupMapper.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpClientFailureAsyncClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpClientFailureClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRedirectsAsyncClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRedirectsClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRetryAsyncClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpRetryClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpSuccessAsyncClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/HttpSuccessClient.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpClientFailuresImpl.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpRedirectsImpl.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpRetriesImpl.java
  protocol-tests/src/main/java/fixtures/httpinfrastructure/implementation/HttpSuccessImpl.java
  vanilla-tests/pom.xml
  vanilla-tests/src/main/java/fixtures/httpinfrastructure/HttpClientFailures.java
  vanilla-tests/src/main/java/fixtures/httpinfrastructure/HttpRedirects.java
  vanilla-tests/src/main/java/fixtures/httpinfrastructure/HttpRetries.java
  vanilla-tests/src/main/java/fixtures/httpinfrastructure/HttpSuccess.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpClientFailureTests.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpFailureTests.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpRedirectTests.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpRetryTests.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpServerFailureTests.java
  vanilla-tests/src/test/java/fixtures/httpinfrastructure/HttpSuccessTests.java
Labels: v4

#1261 llc, fix autorest core version in test
  protocol-sdk-integration-tests/test.py
Labels: LLC

#1262 mgmt, fix bug in LRO context
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
Labels: Mgmt

#1267 LLC, add service-name option to readme
  readme.md
Labels: LLC

#1268 Add Support for Custom Http Exception Type Mappings
  androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
  generate
  generate.bat
  javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClassType.java
  readme.md
  vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/AutoRestHeadExceptionTestService.java
  vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/AutoRestHeadExceptionTestServiceBuilder.java
  vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/HeadExceptions.java
  vanilla-tests/src/main/java/fixtures/customhttpexceptionmapping/package-info.java
  vanilla-tests/src/test/java/fixtures/customhttpexceptionmapping/ValidateExceptionMappingTests.java
  vanilla-tests/swagger/custom-http-exception-mapping.md
Labels: v4
