Repository Azure/autorest.java, pull requests merged in 2022-08, with the labels that each got.

#1592 dpg, fix bug on required ctor fields transformation
  generate
  generate.bat
  javagen/src/main/java/com/azure/autorest/model/clientmodel/PrimitiveType.java
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/RequiredFieldsAsCtorArgsTransformation.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/RequiredFieldsAsCtorArgsTransformationBuilder.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/models/TransformationAsParentRequiredFields.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/models/TransformationAsRequiredFields.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/models/package-info.java
  vanilla-tests/src/main/java/fixtures/requiredfieldsascotrargstransformation/package-info.java
  vanilla-tests/swagger/required-fields-as-ctor-args-transformation.json
Labels: DPG, DPG/RLC v2.0b1, DPG/RLC August MVP

#1596 cadl, concat model name with name from template argument for a template
  cadl-extension/src/code-model-builder.ts
Labels: DPG

#1597 cadl, support content-type
  cadl-extension/src/code-model-builder.ts
  cadl-tests/cadl/patch.cadl
  cadl-tests/src/main/java/com/cadl/patch/JsonMergePatchAsyncClient.java
  cadl-tests/src/main/java/com/cadl/patch/JsonMergePatchClient.java
  cadl-tests/src/main/java/com/cadl/patch/JsonMergePatchClientBuilder.java
  cadl-tests/src/main/java/com/cadl/patch/JsonMergePatchServiceVersion.java
  cadl-tests/src/main/java/com/cadl/patch/implementation/JsonMergePatchClientImpl.java
  cadl-tests/src/main/java/com/cadl/patch/implementation/PatchesImpl.java
  cadl-tests/src/main/java/com/cadl/patch/implementation/package-info.java
  cadl-tests/src/main/java/com/cadl/patch/models/Resource.java
  cadl-tests/src/main/java/com/cadl/patch/models/package-info.java
  cadl-tests/src/main/java/com/cadl/patch/package-info.java
  cadl-tests/src/main/resources/cadl-patch.properties
Labels: DPG

#1607 DPG, refactor createClientMethods to take isProtocolMethod
  androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidClientMethodMapper.java
  androidgen/src/main/java/com/azure/autorest/android/mapper/AndroidProxyMethodMapper.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentClientMethodMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientParameterMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ProxyParameterMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ParameterSynthesizedOrigin.java
  javagen/src/main/java/com/azure/autorest/util/MethodUtil.java
Labels: DPG

#1611 Cadl add optional tests
  cadl-tests/cadl/optional.cadl
  cadl-tests/generate.sh
  cadl-tests/src/main/java/com/cadl/optional/OptionalAsyncClient.java
  cadl-tests/src/main/java/com/cadl/optional/OptionalClient.java
  cadl-tests/src/main/java/com/cadl/optional/OptionalClientBuilder.java
  cadl-tests/src/main/java/com/cadl/optional/OptionalServiceVersion.java
  cadl-tests/src/main/java/com/cadl/optional/implementation/OptionalClientImpl.java
  cadl-tests/src/main/java/com/cadl/optional/implementation/OptionalOpsImpl.java
  cadl-tests/src/main/java/com/cadl/optional/implementation/package-info.java
  cadl-tests/src/main/java/com/cadl/optional/models/AllPropertiesOptional.java
  cadl-tests/src/main/java/com/cadl/optional/models/Optional.java
  cadl-tests/src/main/java/com/cadl/optional/models/OptionalOpsPutHeaders.java
  cadl-tests/src/main/java/com/cadl/optional/models/OptionalOpsPutResponse.java
  cadl-tests/src/main/java/com/cadl/optional/models/package-info.java
  cadl-tests/src/main/java/com/cadl/optional/package-info.java
  cadl-tests/src/main/resources/cadl-optional.properties
Labels: DPG, DPG/RLC v2.0b1

#1608 Better Handling for TypeReference
  javagen/src/main/java/com/azure/autorest/model/clientmodel/GenericType.java
  javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java
  protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java
  protocol-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java
  protocol-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java
  protocol-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java
  protocol-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java
  protocol-tests/src/main/java/fixtures/specialheader/implementation/HeadersImpl.java
  vanilla-tests/src/main/java/fixtures/lro/LRORetrys.java
  vanilla-tests/src/main/java/fixtures/lro/LROs.java
  vanilla-tests/src/main/java/fixtures/lro/LROsCustomHeaders.java
  vanilla-tests/src/main/java/fixtures/lro/LrosaDs.java
Labels: v4

#1619 mgmt, generate examples only for json payload methods
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
Labels: Mgmt

#1595 dpg, fix getEndpoint from client
  androidgen/src/main/java/com/azure/autorest/android/model/clientmodel/AndroidServiceClient.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientBuilderTrait.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClient.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ServiceClientProperty.java
  javagen/src/main/java/com/azure/autorest/template/ServiceAsyncClientTemplate.java
  javagen/src/main/java/com/azure/autorest/template/ServiceSyncClientTemplate.java
Labels: DPG

#1663 add `service-name` to java.json
  cadl-extension/src/main/java/com/azure/autorest/CadlPlugin.java
  cadl-extension/src/main/java/com/azure/cadl/Main.java
  cadl-tests/src/main/java/com/cadl/longrunning/LongRunningAsyncClient.java
  cadl-tests/src/main/java/com/cadl/longrunning/LongRunningClient.java
Labels: DPG/RLC v2.0b1
