Repository Azure/autorest.java, pull requests merged in 2022-04, with the labels that each got.

#1414 dpg, add slf4j-simple to pom
  androidgen/pom.xml
  azure-tests/pom.xml
  customization-base/src/main/resources/pom.xml
  customization-tests/pom.xml
  fluent-tests/pom.xml
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentPomMapper.java
  fluentnamer/pom.xml
  javagen/pom.xml
  javagen/src/main/java/com/azure/autorest/mapper/PomMapper.java
  javagen/src/main/java/com/azure/autorest/model/projectmodel/Project.java
  package.json
  partial-update-tests/pom.xml
  protocol-resilience-test/pom.xml
  protocol-tests/pom.xml
  vanilla-tests/pom.xml
Labels: DPG

#1417 DPG, option data-plane (previously low-level-client)
  docs/generate/dataplane.md
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
  generate
  generate.bat
  partial-update-tests/existing/swagger/README.md
  preprocessor/readme.md
  protocol-sdk-integration-tests/test.py
  protocol-tests/swagger/custom-http-exception-mapping.md
  readme.md
Labels: DPG

#1418 mgmt, bug fix on schema cleanup
  extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ChoiceValue.java
  fluent-tests/prepare-tests.bat
  fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
  fluent-tests/swagger/schema-cleanup.json
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaCleanup.java
  fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/SchemaNameNormalization.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
  vanilla-tests/src/main/java/fixtures/nonstringenum/models/package-info.java
Labels: Client, Mgmt

#1425 dpg, fix partial update test after rename asyncClient to client
  partial-update-tests/existing/src/main/java/fixtures/bodystring/StringOperationClient.java
  partial-update-tests/generated/src/main/java/fixtures/bodystring/StringOperationClient.java
Labels: DPG

#1426 mgmt, bug fix on unused Header class
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/examplemodel/FluentClientMethodExample.java
  javagen/src/main/java/com/azure/autorest/mapper/ClientMapper.java
  javagen/src/main/java/com/azure/autorest/template/ServiceClientBuilderTemplate.java
  package.json
Labels: DPG

#1431 Updates to Headers Deserialization
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
  vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseBoolHeaders.java
  vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseDoubleHeaders.java
  vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseFloatHeaders.java
  vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseIntegerHeaders.java
  vanilla-tests/src/main/java/fixtures/customheaderdeserialization/models/HeadersResponseLongHeaders.java
Labels: v4
