Repository Azure/autorest.java, pull requests merged in 2022-09, with the labels that each got.

#1719 cadl, handle special headers
  cadl-extension/src/code-model-builder.ts
  cadl-tests/cadl/special-headers.cadl
  cadl-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersAsyncClient.java
  cadl-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersClient.java
  cadl-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersClientBuilder.java
  cadl-tests/src/main/java/com/cadl/specialheaders/SpecialHeadersServiceVersion.java
  cadl-tests/src/main/java/com/cadl/specialheaders/implementation/SpecialHeadersClientImpl.java
  cadl-tests/src/main/java/com/cadl/specialheaders/implementation/SpecialHeadersOpsImpl.java
  cadl-tests/src/main/java/com/cadl/specialheaders/implementation/package-info.java
  cadl-tests/src/main/java/com/cadl/specialheaders/models/Resource.java
  cadl-tests/src/main/java/com/cadl/specialheaders/models/package-info.java
  cadl-tests/src/main/java/com/cadl/specialheaders/package-info.java
  cadl-tests/src/main/resources/cadl-specialheaders.properties
Labels: DPG

#1744 Use PowerShell Scripts instead of Bash or Batch
  Generate.ps1
  cadl-tests/Generate.ps1
  cadl-tests/Setup.ps1
  eng/pipelines/cadl-ci.yaml
  eng/pipelines/ci.yaml
  generate.bat
Labels: EngSys

#1750 mgmt, not allow client-flatten on polymorphic schema
  extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/Property.java
  fluent-tests/prepare-tests.bat
  fluent-tests/src/test/java/com/azure/mgmttest/CompilationTests.java
  fluentnamer/src/main/java/com/azure/autorest/fluentnamer/FluentNamer.java
  preprocessor/src/main/java/com/azure/autorest/preprocessor/Preprocessor.java
  preprocessor/src/main/java/com/azure/autorest/preprocessor/tranformer/Transformer.java
Labels: Mgmt
