Repository Azure/autorest.java, pull requests merged in 2022-05, with the labels that each got.

#1446 mgmt, support resourceGroupName() method
  fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
  fluent-tests/src/test/java/com/azure/mgmttest/RuntimeTests.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ResourceParser.java
Labels: Mgmt

#1445 mgmt, use CoreUtils.mergeContext
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentServiceClientTemplate.java
Labels: Mgmt

#1447 mgmt, improve javadoc of Manager
  fluentgen/src/main/java/com/azure/autorest/fluent/model/clientmodel/FluentManagerProperty.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentManagerTemplate.java
Labels: Mgmt

#1448 Added Ability to Customize Constants and Miscellaneous Improvements
  customization-base/src/main/java/com/azure/autorest/customization/AnnotationCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/ClassCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/CodeCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/ConstantCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/ConstructorCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/JavadocCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/MethodCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/PropertyCustomization.java
  customization-base/src/main/java/com/azure/autorest/customization/implementation/Utils.java
Labels: v4

#1458 dpg, disable send request method
  docs/generate/dataplane.md
  extension-base/src/main/java/com/azure/autorest/extension/base/plugin/JavaSettings.java
  protocol-tests/src/main/java/fixtures/dpgcustomization/DpgAsyncClient.java
  protocol-tests/src/main/java/fixtures/dpgcustomization/DpgClient.java
  protocol-tests/src/main/java/fixtures/dpgcustomization/implementation/DpgClientImpl.java
  protocol-tests/src/main/java/fixtures/llcupdate1/DpgAsyncClient.java
  protocol-tests/src/main/java/fixtures/llcupdate1/DpgClient.java
  protocol-tests/src/main/java/fixtures/llcupdate1/implementation/ParamsImpl.java
  protocol-tests/src/main/java/fixtures/parameterizedendpoint/ParmaterizedEndpointAsyncClient.java
  protocol-tests/src/main/java/fixtures/parameterizedendpoint/ParmaterizedEndpointClient.java
  protocol-tests/src/main/java/fixtures/parameterizedendpoint/implementation/ParmaterizedEndpointClientImpl.java
  protocol-tests/src/test/java/fixtures/dpgcustomization/DpgCustomizationTests.java
  protocol-tests/src/test/java/fixtures/dpgcustomization/DpgSendRequestTests.java
  protocol-tests/src/test/java/fixtures/dpgupdate/DpgUpdateTests.java
  protocol-tests/src/test/java/fixtures/parameterizedendpoint/ParameterizedEndpointTests.java
  vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceAsyncClient.java
  vanilla-tests/src/main/java/fixtures/bodydictionary/AutoRestSwaggerBATDictionaryServiceClient.java
  vanilla-tests/src/main/java/fixtures/bodydictionary/implementation/DictionariesImpl.java
Labels: DPG

#1469 mgmt, choose parent with polymorphic
  javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java
Labels: Mgmt

#1470 dpg, generate swagger/readme.md
  javagen/pom.xml
  javagen/src/main/java/com/azure/autorest/Javagen.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
  javagen/src/main/java/com/azure/autorest/model/javamodel/JavaPackage.java
  javagen/src/main/java/com/azure/autorest/template/ModelTestTemplate.java
  javagen/src/main/java/com/azure/autorest/template/SwaggerReadmeTemplate.java
  javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
  javagen/src/main/java/com/azure/autorest/util/ModelTestCaseUtil.java
  javagen/src/main/java/com/azure/autorest/util/TemplateUtil.java
  javagen/src/main/resources/data-plane.md
  preprocessor/data-plane.md
  preprocessor/pom.xml
  preprocessor/readme.md
  protocol-sdk-integration-tests/data-specs.json
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/CookiecuttersharkTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishMarketTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotFishTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/DotSalmonTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/FishTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/GoblinsharkTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyBaseTypeTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/MyDerivedTypeTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/ReadonlyObjTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SalmonTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SawsharkTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SharkTests.java
  vanilla-tests/src/test/java/fixtures/bodycomplex/generated/SmartSalmonTests.java
Labels: DPG

#1471 dpg, sample gen compatible with List/Iterable
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/ExampleParser.java
  javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
  protocol-tests/src/samples/java/fixtures/url/multi/generated/QueriesArrayStringMultiValid.java
Labels: DPG

#1473 dpg, add dpg-archboard-review.md
  docs/developer/2022-05-18-dpg-archboard-review.md
Labels: DPG

#1479 dpg, fix sample gen, for the List type and primitive type with no value
  javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
Labels: DPG

#1475 Prepare azure-autorest-customization for release
  androidgen/pom.xml
  azure-tests/pom.xml
  customization-base/CHANGELOG.md
  customization-base/README.md
  customization-base/pom.xml
  customization-tests/swagger/pom.xml
  extension-base/pom.xml
  fluent-tests/pom.xml
  fluentgen/pom.xml
  fluentnamer/pom.xml
  javagen/pom.xml
  partial-update-tests/pom.xml
  pom.xml
  postprocessor/pom.xml
  postprocessor/src/main/resources/readme/pom.xml
  preprocessor/pom.xml
  protocol-resilience-test/pom.xml
  protocol-tests/pom.xml
  vanilla-tests/pom.xml
Labels: Codegen Customizations

#1480 dpg, add examples to test swagger
  javagen/src/main/java/com/azure/autorest/template/example/ProtocolExampleWriter.java
  javagen/src/main/java/com/azure/autorest/util/ModelExampleUtil.java
  protocol-tests/src/main/java/fixtures/requiredheaderquery/DpgRequiredHeaderQueryAsyncClient.java
  protocol-tests/src/main/java/fixtures/requiredheaderquery/DpgRequiredHeaderQueryClient.java
  protocol-tests/src/main/java/fixtures/requiredheaderquery/implementation/ParamsImpl.java
  protocol-tests/src/samples/java/fixtures/requiredheaderquery/generated/HeaderParamters.java
  protocol-tests/src/samples/java/fixtures/requiredheaderquery/generated/QueryParamters.java
  protocol-tests/swagger/examples/dpg-header-parameters.json
  protocol-tests/swagger/examples/dpg-query-parameters.json
  protocol-tests/swagger/required-header-query.json
Labels: DPG
