Repository Azure/autorest.java, pull requests merged in 2023-03, with the labels that each got.

#2006 eng, upgrade github action to latest
  .github/workflows/fluent-test-gen-all.yml
  .github/workflows/generate-test-code.yml
  .github/workflows/pre-release-cadl.yml
  .github/workflows/pre-release.yml
Labels: EngSys

#2016 cadl, fix regression on BinaryResponse
  cadl-extension/src/code-model-builder.ts
  cadl-tests/src/main/java/com/cadl/response/ResponseAsyncClient.java
  cadl-tests/src/main/java/com/cadl/response/ResponseClient.java
  cadl-tests/src/main/java/com/cadl/response/implementation/ResponseClientImpl.java
Labels: DPG

#2020 Support Descriptions in Enum Values
  azure-dataplane-tests/src/main/java/com/azure/ai/formrecognizer/documentanalysis/implementation/models/ContentType.java
  azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactArchitecture.java
  azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactManifestOrder.java
  azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/ArtifactTagOrder.java
  cadl-tests/src/main/java/com/models/property/types/models/FixedInnerEnum.java
  cadl-tests/src/main/java/com/models/property/types/models/InnerEnum.java
  customization-tests/src/main/java/fixtures/bodycomplex/implementation/models/GoblinSharkColor.java
  extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/ChoiceSchema.java
  extension-base/src/main/java/com/azure/autorest/extension/base/model/codemodel/SealedChoiceSchema.java
  javagen/src/main/java/com/azure/autorest/mapper/ChoiceMapper.java
  javagen/src/main/java/com/azure/autorest/mapper/MapperUtils.java
  javagen/src/main/java/com/azure/autorest/mapper/SealedChoiceMapper.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientEnumValue.java
  javagen/src/main/java/com/azure/autorest/model/javamodel/JavaEnum.java
  javagen/src/main/java/com/azure/autorest/template/EnumTemplate.java
  vanilla-tests/src/main/java/fixtures/bodycomplex/models/GoblinSharkColor.java
  vanilla-tests/src/main/java/fixtures/extensibleenums/models/IntEnum.java
  vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType.java
  vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType1.java
  vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType2.java
  vanilla-tests/src/main/java/fixtures/mediatypes/models/ContentType3.java
  vanilla-tests/src/main/java/fixtures/streamstyleserialization/models/GoblinSharkColor.java
Labels: v4

#2021 Create Script to Generate CADL
  Generate-TypeSpec.ps1
  eng/pipelines/ci-cadl-java.yaml
Labels: v4

#2032 Set Default Value when Stream-Style Serialization is Used
  azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/implementation/models/PathsV3R3RxOauth2TokenPostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java
  javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java
Labels: v4

#2033 mgmt, bug fix on proxy method default Exception
  azure-dataplane-tests/src/main/java/com/azure/containers/containerregistry/models/OciImageManifest.java
  fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java
  fluentgen/src/main/java/com/azure/autorest/fluent/checker/JavaFormatter.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/SampleTemplate.java
  fluentgen/src/test/java/com/azure/autorest/fluent/checker/JavaFormatterTests.java
  javagen/src/main/java/com/azure/autorest/mapper/ProxyMethodMapper.java
  package.json
Labels: Mgmt
