Repository Azure/autorest.java, pull requests merged in 2023-02, with the labels that each got.

#1980 Update pool used by `eng/pipelines/fluent_integration.yaml` to azsdk-pool-mms-win-2022-general / MMS2022Compliant
  eng/pipelines/fluent_integration.yaml
Labels: Central-EngSys

#1985 mgmt, fix LRO + pageable
  Generate.ps1
  azure-tests/src/main/java/fixtures/lro/fluent/LROsClient.java
  azure-tests/src/main/java/fixtures/lro/fluent/LroRetrysClient.java
  azure-tests/src/main/java/fixtures/lro/fluent/LrosCustomHeadersClient.java
  azure-tests/src/main/java/fixtures/lro/fluent/LrosaDsClient.java
  azure-tests/src/main/java/fixtures/lro/implementation/LROsClientImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LROsImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysClientImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LroRetrysImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersClientImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LrosCustomHeadersImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsClientImpl.java
  azure-tests/src/main/java/fixtures/lro/implementation/LrosaDsImpl.java
  azure-tests/src/main/java/fixtures/lro/models/LROs.java
  azure-tests/src/main/java/fixtures/lro/models/LroRetrys.java
  azure-tests/src/main/java/fixtures/lro/models/LrosCustomHeaders.java
  azure-tests/src/main/java/fixtures/lro/models/LrosaDs.java
  azure-tests/src/main/java/fixtures/lro/models/ProductPropertiesProvisioningStateValues.java
  azure-tests/src/main/java/fixtures/lro/models/SubProductPropertiesProvisioningStateValues.java
  azure-tests/src/main/java/fixtures/lroparameterizedendpoints/implementation/ResourceProvidersClientImpl.java
  azure-tests/src/test/java/fixtures/lro/LroTests.java
  fluent-tests/prepare-tests.bat
  fluent-tests/spotbugs-exclude.xml
  fluent-tests/src/test/java/com/azure/mgmttest/LiteCompilationTests.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/FluentMapper.java
  fluentgen/src/main/java/com/azure/autorest/fluent/mapper/MockTestParser.java
  fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentClientMethodTemplate.java
  javagen/src/main/java/com/azure/autorest/model/clientmodel/ClientMethod.java
Labels: Mgmt

#1995 Upgrade Node Version to a Consistent Version
  eng/pipelines/ci-cadl-java.yaml
  eng/pipelines/ci.yaml
  eng/pipelines/fluent_integration.yaml
  eng/pipelines/publish-autorest-java.yaml
  eng/pipelines/publish-cadl-java.yaml
Labels: EngSys
